"gun_joe_machine_gun"
{
	// General
	//-------------------------------------------------------------------------------------------------------------
	"BaseClass"						"ability_lua"
	"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_TOGGLE | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
	
	"AbilityTextureName"			"custom/gun_joe_machine_gun_2"
	"ScriptFile"					"heroes/gun_joe/gun_joe_machine_gun.lua"
	
	"MaxLevel"						"7"
	
	// Casting
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCastRange"				"0"
	"AbilityCastPoint"				"0.0"

	// Time		
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCooldown"				"0.0"

	// Cost
	//-------------------------------------------------------------------------------------------------------------
	"AbilityManaCost"				"0"

	// Special
	//-------------------------------------------------------------------------------------------------------------
	"AbilitySpecial"
	{
		"01"
		{
			"var_type"				"FIELD_INTEGER"
			"attack_range"			"-180 -170 -160 -150 -140 -130 -120"
		}
		"02"
		{
			"var_type"				"FIELD_FLOAT"
			"bat"					"0.7"
		}
		"03"
		{
			"var_type"				"FIELD_FLOAT"
			"damage_decrease_pct"	"-55 -52 -50 -48 -46 -43 -40"
		}
	}
}

"gun_joe_rifle"
{
	// General
	//-------------------------------------------------------------------------------------------------------------
	"BaseClass"						"ability_lua"
	"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_TOGGLE | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
	
	"AbilityTextureName"			"custom/gun_joe_rifle"
	"ScriptFile"					"heroes/gun_joe/gun_joe_rifle.lua"
	
	"MaxLevel"						"7"
	
	// Casting
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCastRange"				"0"
	"AbilityCastPoint"				"0.0"

	// Time		
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCooldown"				"0.0"

	// Cost
	//-------------------------------------------------------------------------------------------------------------
	"AbilityManaCost"				"0"

	// Special
	//-------------------------------------------------------------------------------------------------------------
	"AbilitySpecial"
	{
		"01"
		{
			"var_type"				"FIELD_INTEGER"
			"attack_range"			"75 100 125 150 200 250 300"
		}
		"02"
		{
			"var_type"				"FIELD_FLOAT"
			"bat"					"1.85"
		}
		"03"
		{
			"var_type"				"FIELD_FLOAT"
			"damage_increase_pct"	"10 12 14 16 18 20 22"
		}
	}
}

"gun_joe_rapid"
{
	// General
	//-------------------------------------------------------------------------------------------------------------
	"BaseClass"						"ability_lua"
	"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE"
	"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_NO"
	"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"	
	"AbilityTextureName"			"custom/gun_joe_rapid"
	"ScriptFile"					"heroes/gun_joe/rapid.lua"
	
	"MaxLevel"						"7"
	"FightRecapLevel"				"2"
	
	// Casting
	//-------------------------------------------------------------------------------------------------------------

	// Time		
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCooldown"				"3.0"

	// Cost
	//-------------------------------------------------------------------------------------------------------------
	"AbilityManaCost"				"0"

	// Special
	//-------------------------------------------------------------------------------------------------------------
	"AbilitySpecial"
	{
		"01"
		{
			"var_type"					"FIELD_FLOAT"
			"cooldown"					"3.0"
			"LinkedSpecialBonus"		"gun_joe_special_bonus_rapid_cd"
		}
		"02"
		{
			"var_type"					"FIELD_INTEGER"
			"bonus_movespeed"			"10 15 20 25 30 35 40"
		}
		"03"
		{
			"var_type"					"FIELD_FLOAT"
			"bonus_attackspeed"			"40 60 80 100 120 140 160"
		}
	}
}

"gun_joe_explosive"
{
	// General
	//-------------------------------------------------------------------------------------------------------------
	"BaseClass"						"ability_lua"
	"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
	"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
	
	"AbilityTextureName"			"custom/gun_joe_explosive"
	"ScriptFile"					"heroes/gun_joe/explosive.lua"
	
	"MaxLevel"						"7"
	"FightRecapLevel"				"2"
	
	// Casting
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCastRange"				"0"
	"AbilityCastPoint"				"0.0"

	// Time		
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCooldown"				"16.0"

	// Cost
	//-------------------------------------------------------------------------------------------------------------
	"AbilityManaCost"				"50 70 90 110 130 150 170"

	// Special
	//-------------------------------------------------------------------------------------------------------------
	"AbilitySpecial"
	{
		"01"
		{
			"var_type"					"FIELD_FLOAT"
			"cooldown"					"16.0"
			"LinkedSpecialBonus"		"gun_joe_special_bonus_explosive_bullets_cd"
		}
		"02"
		{
			"var_type"					"FIELD_INTEGER"
			"stack_count"				"6"
			"LinkedSpecialBonus"		"gun_joe_special_bonus_explosive_bullets_stack"
		}
		"03"
		{
			"var_type"					"FIELD_INTEGER"
			"bonus_damage"				"30 40 50 60 70 80 90"
		}
		"04"
		{
			"var_type"					"FIELD_FLOAT"
			"radius"					"230"
			"LinkedSpecialBonus"		"gun_joe_special_bonus_explosive_bullets_radius"
		}
		"05"
		{
			"var_type"					"FIELD_FLOAT"
			"duration"					"16.0"
		}
	}
}

"gun_joe_calibrated_shot"
{
	// General
	//-------------------------------------------------------------------------------------------------------------
	"BaseClass"						"ability_lua"
	"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_AUTOCAST | DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING"
	"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
	"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC | DOTA_UNIT_TARGET_BUILDING"
	"AbilityUnitDamageType"			"DAMAGE_TYPE_PHYSICAL"
	"AbilityType"					"DOTA_ABILITY_TYPE_ULTIMATE"
	
	"AbilityTextureName"			"custom/gun_joe_calibrated_shot"
	"ScriptFile"					"heroes/gun_joe/gun_joe_calibrated_shot.lua"
	
	"MaxLevel"						"7"
	
	"precache"
	{
		"soundfile" 				"soundevents/game_sounds_heroes/game_sounds_sniper.vsndevts"
		"particle" 					"particles/units/heroes/hero_sniper/sniper_assassinate.vpcf"
		"particle" 					"particles/generic_gameplay/generic_stunned.vpcf"
	}
	
	// Casting
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCastRange"				"0"
	"AbilityCastPoint"				"1.0"

	// Time		
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCooldown"				"25.0"

	// Cost
	//-------------------------------------------------------------------------------------------------------------
	"AbilityManaCost"				"60 70 80 90 100 110 120"

	// Special
	//-------------------------------------------------------------------------------------------------------------
	"AbilitySpecial"
	{
		"01"
		{
			"var_type"				"FIELD_FLOAT"
			"stun_duration"			"2.0"
		}
		"02"
		{
			"var_type"				"FIELD_FLOAT"
			"damage_from_attack"	"130 135 140 145 150 155 160"
		}
		"03"
		{
			"var_type"				"FIELD_FLOAT"
			"bonus_attack_range"	"600"
		}
		"04"
		{
			"var_type"				"FIELD_FLOAT"
			"projectile_speed"		"2200"
		}
	}
}
