"npc_dota_hero_puck"
{
	"ArmorPhysical"		"1"

	"AttackDamageMin"		"22"
	"AttackDamageMax"		"33"
	"AttackRate"			"1.7"
	"AttackAnimationPoint"	"0.500000"
	"AttackAcquisitionRange"	"800"
	"AttackRange"			"550"

	"AttributePrimary"			"DOTA_ATTRIBUTE_INTELLECT"
	"AttributeBaseStrength"		"22"
	"AttributeStrengthGain"		"2.100000"
	"AttributeBaseIntelligence"	"25"
	"AttributeIntelligenceGain"	"3.200000"
	"AttributeBaseAgility"		"22"
	"AttributeAgilityGain"		"2.200000"
	"MovementSpeed"				"300"
}