"npc_dota_hero_slark"
{
	"ArmorPhysical"				"0"

	"AttackDamageMin"			"27"
	"AttackDamageMax"			"33"
	"AttackRate"				"1.7"
	
	"AttributePrimary"			"DOTA_ATTRIBUTE_AGILITY"
	"AttributeBaseStrength"		"21"
	"AttributeStrengthGain"		"2.2"
	"AttributeBaseIntelligence"	"16"
	"AttributeIntelligenceGain"	"2.2"
	"AttributeBaseAgility"		"21"
	"AttributeAgilityGain"		"3.2"
	
	"VisionDaytimeRange"		"1800"
	"VisionNighttimeRange"		"1800"
	"MovementSpeed"				"305"
	"MovementTurnRate"			"0.5"
}