"npc_dota_hero_abyssal_underlord"
{
	"ArmorPhysical"					"2.000000"
	
	"AttackDamageMin"				"37"
	"AttackDamageMax"				"43"
	"AttackRate"					"1.600000"

	"AttributePrimary"				"DOTA_ATTRIBUTE_STRENGTH"
	"AttributeBaseStrength"			"30"
	"AttributeStrengthGain"			"2.600000"
	"AttributeBaseAgility"			"12"
	"AttributeAgilityGain"			"2.000000"
	"AttributeBaseIntelligence"		"17"
	"AttributeIntelligenceGain"		"2.600000"
	"MovementSpeed"					"305"
	"MovementTurnRate"				"0.600000"
}