"npc_dota_hero_axe"
{
	"ArmorPhysical"		"0"
	"AttackRate"		"1.7"
	"AttackDamageMin"		"24"
	"AttackDamageMax"		"28"
	
	"AttributePrimary"				"DOTA_ATTRIBUTE_STRENGTH"
	"AttributeBaseStrength"			"25"
	"AttributeStrengthGain"			"3.200000"
	"AttributeBaseIntelligence"		"18"
	"AttributeIntelligenceGain"		"1.600000"
	"AttributeBaseAgility"			"20"
	"AttributeAgilityGain"			"2.200000"
	
	"StatusHealthRegen"				"7"
}