"npc_dota_hero_bane"
{
	"ArmorPhysical"		"1"

	"AttackDamageMin"		"33"
	"AttackDamageMax"		"39"
	"AttackRate"		"1.7"

	"AttackRange"		"500"

	"AttributePrimary"		"DOTA_ATTRIBUTE_INTELLECT"
	"AttributeBaseStrength"		"22"
	"AttributeStrengthGain"		"2.400000"
	"AttributeBaseIntelligence"		"22"
	"AttributeIntelligenceGain"		"3.2"
	"AttributeBaseAgility"		"22"
	"AttributeAgilityGain"		"2.400000"
	"MovementSpeed"		"310"
}