"npc_dota_hero_bounty_hunter"
{
	"ArmorPhysical"		"0"
	"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
	"AttackDamageMin"		"24"
	"AttackDamageMax"		"38"
	"AttackRate"		"1.7"

	"AttributePrimary"		"DOTA_ATTRIBUTE_AGILITY"
	"AttributeBaseStrength"		"26"
	"AttributeStrengthGain"		"2.7"
	"AttributeBaseAgility"		"21"
	"AttributeAgilityGain"		"2.900000"
	"AttributeBaseIntelligence"		"19"
	"AttributeIntelligenceGain"		"2.400000"
	"MovementSpeed"		"315"
}