"npc_dota_hero_bounty_hunter"
{
	"ArmorPhysical"					"2"
	"AttackCapabilities"			"DOTA_UNIT_CAP_MELEE_ATTACK"
	"AttackDamageMin"				"24"
	"AttackDamageMax"				"38"
	"AttackRate"					"1.7"

	"AttributePrimary"				"DOTA_ATTRIBUTE_AGILITY"
	"AttributeBaseStrength"			"21"
	"AttributeStrengthGain"			"2.7"
	"AttributeBaseAgility"			"26"
	"AttributeAgilityGain"			"3.200000"
	"AttributeBaseIntelligence"		"19"
	"AttributeIntelligenceGain"		"1.800000"
	"MovementSpeed"					"315"
}