"npc_dota_hero_dark_seer"
{
	"AttackDamageMin"		"31"
	"AttackDamageMax"		"37"
	"AttackRate"		"1.7"
	"ArmorPhysical"		"0"
	"AttributePrimary"		"DOTA_ATTRIBUTE_INTELLECT"
	"AttributeBaseStrength"		"22"
	"AttributeStrengthGain"		"2.800000"
	"AttributeBaseAgility"		"18"
	"AttributeAgilityGain"		"2.200000"
	"AttributeBaseIntelligence"		"25"
	"AttributeIntelligenceGain"		"2.900000"
	"MovementSpeed"		"300"
	
}