"npc_dota_hero_dazzle"
{
	"AttackDamageMin"		"14"
	"AttackDamageMax"		"32"
	"AttackRate"		"1.7"
	"AttackAnimationPoint"		"0.300000"
	"AttackAcquisitionRange"		"800"
	"AttackRange"		"550"

	"AttributePrimary"		"DOTA_ATTRIBUTE_INTELLECT"
	"AttributeBaseStrength"		"20"
	"AttributeStrengthGain"		"2.40000"
	"AttributeBaseIntelligence"		"27"
	"AttributeIntelligenceGain"		"3.400000"
	"AttributeBaseAgility"		"21"
	"AttributeAgilityGain"		"2.000000"
	"MovementSpeed"		"305"
}