"npc_dota_hero_disruptor"
{
	"ArmorPhysical"		"0.000000"

	"AttackDamageMin"		"27"
	"AttackDamageMax"		"31"
	"AttackRate"		"1.7"


	"AttributePrimary"		"DOTA_ATTRIBUTE_INTELLECT"
	"AttributeBaseStrength"		"19"
	"AttributeStrengthGain"		"2.500000"
	"AttributeBaseAgility"		"18"
	"AttributeAgilityGain"		"2.400000"
	"AttributeBaseIntelligence"		"25"
	"AttributeIntelligenceGain"		"2.800000"
	
	"MovementSpeed"		"300"
}