"npc_dota_hero_dragon_knight"
{
	"ArmorPhysical"					"1"
	

	"AttackDamageMin"				"27"
	"AttackDamageMax"				"33"
	
	"AttackRate"					"1.7"
	"AttackAnimationPoint"			"0.500000"
	
	"AttributePrimary"				"DOTA_ATTRIBUTE_STRENGTH"
	"AttributeBaseStrength"			"19"
	"AttributeStrengthGain"			"2.800000"
	"AttributeBaseAgility"			"19"
	"AttributeAgilityGain"			"2.400000"
	"AttributeBaseIntelligence"		"15"
	"AttributeIntelligenceGain"		"1.800000"
	"MovementSpeed"					"300"
}