"npc_dota_hero_elder_titan"
{
	
	"ArmorPhysical"			"1.0"
	
	"AttackCapabilities"	"DOTA_UNIT_CAP_MELEE_ATTACK"
	"AttackDamageMin"		"23"
	"AttackDamageMax"		"33"
	"AttackRate"			"1.7"


	"AttributePrimary"		"DOTA_ATTRIBUTE_STRENGTH"
	"AttributeBaseStrength"		"24"
	"AttributeStrengthGain"		"3.800000"
	"AttributeBaseAgility"		"14"
	"AttributeAgilityGain"		"2.900000"
	"AttributeBaseIntelligence"		"23"
	"AttributeIntelligenceGain"		"1.900000"
	"MovementSpeed"		"315"
	"MovementTurnRate"		"0.400000"
}