"npc_dota_hero_gun_joe"
{													
		// General
		//-------------------------------------------------------------------------------------------------------------
		"override_hero" "npc_dota_hero_sniper"
		// Abilities
		//-------------------------------------------------------------------------------------------------------------
		"Ability1"					"gun_joe_machine_gun"
		"Ability2"					"gun_joe_rifle"
		"Ability3"					"gun_joe_explosive"
		"Ability4"					"gun_joe_rapid"
		"Ability5"					"generic_hidden"
		"Ability6"					"gun_joe_calibrated_shot"
		
		"Ability10"				"gun_joe_special_bonus_rapid_cd"
		"Ability11"				"gun_joe_special_bonus_explosive_bullets_cd"
		"Ability12"				"special_bonus_attack_speed_20"
		"Ability13"				"special_bonus_hp_250"
		"Ability14"				"gun_joe_special_bonus_explosive_bullets_radius"
		"Ability15"				"gun_joe_special_bonus_explosive_bullets_stack"
		"Ability16"				"special_bonus_agility_25"
		"Ability17"				"special_bonus_armor_15"
		
		"AttackDamageMin"			"35"									// Damage range min.
		"AttackDamageMax"			"37"									// Damage range max.	
		
		"AttackRange"				"500"
		"AttackRate"				"1.7"									// Speed of attack.
		"AttackAnimationPoint"		"0.1"									// Normalized time in animation cycle to attack.
		
		"AttributePrimary"			"DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength"		"20"									// Base strength
		"AttributeStrengthGain"		"2.5"									// Strength bonus per level.
		"AttributeBaseAgility"		"20"									// Base agility
		"AttributeAgilityGain"		"2.5"									// Agility bonus per level.
		"AttributeBaseIntelligence"	"15"									// Base intelligence
		"AttributeIntelligenceGain"	"2.2"									// Intelligence bonus per level.
		
		"MovementSpeed"					"300"
}