"npc_dota_hero_gyrocopter"
{
	"ArmorPhysical"		"0"

	"AttackDamageMin"		"27"
	"AttackDamageMax"		"37"
	"AttackRate"		"1.5"

	"AttackRange"		"365"
	
	"AttributePrimary"		"DOTA_ATTRIBUTE_AGILITY"
	"AttributeBaseStrength"		"22"
	"AttributeStrengthGain"		"2.6"
	"AttributeBaseAgility"		"25"
	"AttributeAgilityGain"		"4.2"
	"AttributeBaseIntelligence"		"19"
	"AttributeIntelligenceGain"		"2.1"
	"MovementSpeed"			"315"
	"MovementTurnRate"		"0.6"

}