"npc_dota_hero_huskar"
{
	"ArmorPhysical"		"1"
	"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
	"AttackDamageMin"		"21"
	"AttackDamageMax"		"30"
	"AttackRate"		"1.7" // 1.6

	"AttributePrimary"		"DOTA_ATTRIBUTE_STRENGTH"
	"AttributeBaseStrength"		"19"
	"AttributeStrengthGain"		"2.700000"
	"AttributeBaseAgility"		"14"
	"AttributeAgilityGain"		"1.40000"
	"AttributeBaseIntelligence"		"18"
	"AttributeIntelligenceGain"		"1.500000"
	"MovementSpeed"		"300"
}