"npc_dota_hero_invoker"
{
	"AttackDamageMin"		"20"
	"AttackDamageMax"		"24"
	"AttackRate"		"1.7"

	"AttackRange"		"550"

	"AttributePrimary"		"DOTA_ATTRIBUTE_INTELLECT"
	"AttributeBaseStrength"		"19"
	"AttributeStrengthGain"		"2.5"
	"AttributeBaseAgility"		"20"
	"AttributeAgilityGain"		"2.5"
	"AttributeBaseIntelligence"		"30"
	"AttributeIntelligenceGain"		"3.0"
	"MovementSpeed"		"305"
	"MovementTurnRate"		"0.500000"
}