"npc_dota_hero_jakiro"
{
	"ArmorPhysical"		"1"

	"AttackDamageMin"		"25"
	"AttackDamageMax"		"33"
	"AttackRate"		"1.7"

	"AttackRange"		"500"
	
	"AttributePrimary"		"DOTA_ATTRIBUTE_INTELLECT"
	"AttributeBaseStrength"		"18"
	"AttributeStrengthGain"		"2.8"
	"AttributeBaseIntelligence"		"28"
	"AttributeIntelligenceGain"		"4.300000"
	"AttributeBaseAgility"		"10"
	"AttributeAgilityGain"		"2.200000"
	"MovementSpeed"		"325"
	
}