"npc_dota_hero_legion_commander"
{
	"ArmorPhysical"		"0.0"
	"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
	"AttackDamageMin"		"35"
	"AttackDamageMax"		"39"
	"AttackRate"		"1.7"

	
	"AttributePrimary"		"DOTA_ATTRIBUTE_STRENGTH"
	"AttributeBaseStrength"		"22"
	"AttributeStrengthGain"		"2.5"
	"AttributeBaseAgility"		"18"
	"AttributeAgilityGain"		"2.0"
	"AttributeBaseIntelligence"		"20"
	"AttributeIntelligenceGain"		"2.2"
	"MovementSpeed"		"320"
}