"npc_dota_hero_lion"
{
	"ArmorPhysical"		"0"
	"AttackDamageMin"		"27"
	"AttackDamageMax"		"33"
	"AttackRate"		"1.7"


	"AttributePrimary"		"DOTA_ATTRIBUTE_INTELLECT"
	"AttributeBaseStrength"		"16"
	"AttributeStrengthGain"		"2.200000"
	"AttributeBaseIntelligence"		"22"
	"AttributeIntelligenceGain"		"3.500000"
	"AttributeBaseAgility"		"15"
	"AttributeAgilityGain"		"2.000000"
	
	"MovementSpeed"		"305"

}