"npc_dota_hero_lion"
{
	"ArmorPhysical"		"0"
	"AttackDamageMin"		"27"
	"AttackDamageMax"		"33"
	"AttackRate"		"1.7"


	"AttributePrimary"		"DOTA_ATTRIBUTE_INTELLECT"
	"AttributeBaseStrength"		"20" // 16
	"AttributeStrengthGain"		"2.200000"
	"AttributeBaseIntelligence"		"26" // 22
	"AttributeIntelligenceGain"		"3.3" // 3.5
	"AttributeBaseAgility"		"18" // 15
	"AttributeAgilityGain"		"2.2" // 2.0
	
	"MovementSpeed"		"305"

}