"npc_dota_hero_nyx_assassin"
{
	"ArmorPhysical"		"1.3"
	"AttackDamageMin"		"35"
	"AttackDamageMax"		"39"
	
	"AttackRate"		"1.7"

	"AttributePrimary"		"DOTA_ATTRIBUTE_AGILITY"
	"AttributeBaseStrength"		"18"
	"AttributeStrengthGain"		"2.5"
	"AttributeBaseAgility"		"21"
	"AttributeAgilityGain"		"3.6"
	"AttributeBaseIntelligence"		"18"
	"AttributeIntelligenceGain"		"3.5"
	"StatusHealthRegen"				"5.500000"
	"MovementSpeed"		"300"
}