"npc_dota_hero_pudge"
{
	"ArmorPhysical"		"0"
	
	"AttackDamageMin"		"27"
	"AttackDamageMax"		"33"
	"AttackRate"		"1.700000"
	
	"AttributePrimary"		"DOTA_ATTRIBUTE_STRENGTH"
	"AttributeBaseStrength"		"25"
	"AttributeStrengthGain"		"3.200000"
	"AttributeBaseIntelligence"		"14"
	"AttributeIntelligenceGain"		"1.500000"
	"AttributeBaseAgility"		"14"
	"AttributeAgilityGain"		"1.500000"
	"MovementSpeed"		"285"
}