"npc_dota_hero_queenofpain"

{
	
	"AttackDamageMin"		"25"
	"AttackDamageMax"		"33"
	"AttackRate"		"1.7"
	"AttackAnimationPoint"		"0.560000"
	"AttackAcquisitionRange"		"800"
	"AttackRange"		"550"

	"AttributePrimary"		"DOTA_ATTRIBUTE_INTELLECT"
	"AttributeBaseStrength"		"20"
	"AttributeStrengthGain"		"2.400000"
	"AttributeBaseIntelligence"		"22"
	"AttributeIntelligenceGain"		"2.800000"
	"AttributeBaseAgility"		"25"
	"AttributeAgilityGain"		"2.3"
	"MovementSpeed"		"305"
	
}