"npc_dota_hero_spirit_breaker"
{
	"ArmorPhysical"		"2.000000"

	"AttackDamageMin"		"35"
	"AttackDamageMax"		"45"
	"AttackRate"		"1.7"

	"AttributePrimary"		"DOTA_ATTRIBUTE_STRENGTH"
	"AttributeBaseStrength"		"31"
	"AttributeStrengthGain"		"3.500000"
	"AttributeBaseAgility"		"20"
	"AttributeAgilityGain"		"3.0"
	"AttributeBaseIntelligence"		"20"
	"AttributeIntelligenceGain"		"1.800000"

	"MovementSpeed"		"305"
}