"npc_dota_hero_spirit_breaker"
{
	"ArmorPhysical"		"2.000000"

	"AttackDamageMin"		"35"
	"AttackDamageMax"		"45"
	"AttackRate"		"1.7"

	"AttributePrimary"		"DOTA_ATTRIBUTE_STRENGTH"
	"AttributeBaseStrength"		"29" // 31
	"AttributeStrengthGain"		"3.3" // 3.5
	"AttributeBaseAgility"		"22" // 20
	"AttributeAgilityGain"		"2.7" // 3.0
	"AttributeBaseIntelligence"		"20"
	"AttributeIntelligenceGain"		"2.3" // 1.8

	"MovementSpeed"		"310" // 305
}