"npc_dota_hero_techies"
{
	"AttackRate"		"1.7"
	"AttackAnimationPoint"		"0.500000"
	"AttackAcquisitionRange"		"800"
	"AttackRange"			"900"
	"AttackDamageMin"		"7"
	"AttackDamageMax"		"9"
	
	"AttributePrimary"		"DOTA_ATTRIBUTE_INTELLECT"
	"AttributeBaseStrength"		"17"
	"AttributeStrengthGain"		"2.000000"
	"AttributeBaseIntelligence"		"22"
	"AttributeIntelligenceGain"		"2.00000"
	"AttributeBaseAgility"		"14"
	"AttributeAgilityGain"		"1.300000"

	"StatusManaRegen"		"1.0"
}