"npc_dota_hero_templar_assassin"
{			
	// Abilities
	//-------------------------------------------------------------------------------------------------------------
	"AttackRange"			"200" // 125
	"AttributeStrengthGain"		"2.6"									// Strength bonus per level.
	"AttributeAgilityGain"		"4.5"									// Agility bonus per level.
	"AttributeIntelligenceGain"	"1.8"	
	"AttackRate"				"1.7"
	"AttackDamageMin"			"36"
	"AttackDamageMax"			"40"
}