"npc_dota_hero_tinker"
{
	"ArmorPhysical"		"2"
	"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
	"AttackDamageMin"		"28"
	"AttackDamageMax"		"32"
	"AttackRate"		"1.700000"

	"AttributePrimary"		"DOTA_ATTRIBUTE_INTELLECT"
	"AttributeBaseStrength"		"17"
	"AttributeStrengthGain"		"2.000000"
	"AttributeBaseIntelligence"		"30"
	"AttributeIntelligenceGain"		"2.200000"
	"AttributeBaseAgility"		"13"
	"AttributeAgilityGain"		"1.200000"
	"MovementSpeed"		"305"

}