"npc_dota_hero_tinker"
{
	"ArmorPhysical"		"2"
	"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
	"AttackDamageMin"		"28"
	"AttackDamageMax"		"32"
	"AttackRate"		"1.700000"

	"AttributePrimary"		"DOTA_ATTRIBUTE_INTELLECT"
	"AttributeBaseStrength"		"19" // 17
	"AttributeStrengthGain"		"2.1" // 2.0
	"AttributeBaseIntelligence"		"28" // 30
	"AttributeIntelligenceGain"		"2.8" // 2.2
	"AttributeBaseAgility"		"17" // 13
	"AttributeAgilityGain"		"1.7" // 1.2
	"MovementSpeed"		"305"

}