"npc_dota_hero_treant"
{
	"ArmorPhysical"		"0"

	"AttackDamageMin"		"56"
	"AttackDamageMax"		"64"
	"AttackRate"		"1.7"
	
	"AttributePrimary"		"DOTA_ATTRIBUTE_STRENGTH"
	"AttributeBaseStrength"		"22"
	"AttributeStrengthGain"		"3.000000"
	"AttributeBaseAgility"		"15"
	"AttributeAgilityGain"		"2.500000"
	"AttributeBaseIntelligence"		"12"
	"AttributeIntelligenceGain"		"2.000000"

	"MovementSpeed"		"295"
	"MovementTurnRate"		"0.500000"
}