"npc_dota_hero_venomancer"
{
	"ArmorPhysical"		"1"
	"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
	"AttackDamageMin"		"29"
	"AttackDamageMax"		"32"
	"AttackRate"		"1.7"

	"AttributePrimary"		"DOTA_ATTRIBUTE_AGILITY"
	"AttributeBaseStrength"		"18"
	"AttributeStrengthGain"		"2.50000"
	"AttributeBaseIntelligence"		"15"
	"AttributeIntelligenceGain"		"2.30000"
	"AttributeBaseAgility"		"22"
	"AttributeAgilityGain"		"2.700000"
	"StatusHealthRegen"		"0.250000"
	"MovementSpeed"		"300"
}