"npc_dota_hero_viper"
{
	"ArmorPhysical"		"1"
	
	"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
	"AttackDamageMin"		"33"
	"AttackDamageMax"		"35"
	"AttackRate"		"1.7"

	"AttackRange"		"575"

	"AttributePrimary"		"DOTA_ATTRIBUTE_AGILITY"
	"AttributeBaseStrength"		"26"
	"AttributeStrengthGain"		"2.200000"
	"AttributeBaseAgility"		"24"
	"AttributeAgilityGain"		"3.300000"
	"AttributeBaseIntelligence"		"15"
	"AttributeIntelligenceGain"		"1.800000"
	"MovementSpeed"		"300"
}