"npc_dota_hero_warlock"
{
	"ArmorPhysical"		"1"
	"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
	"AttackDamageMin"		"22"
	"AttackDamageMax"		"32"
	"AttackRate"		"1.7"

	"AttributePrimary"		"DOTA_ATTRIBUTE_INTELLECT"
	"AttributeBaseStrength"		"22"
	"AttributeStrengthGain"		"2.500000"
	"AttributeBaseIntelligence"		"24"
	"AttributeIntelligenceGain"		"2.900000"
	"AttributeBaseAgility"		"10"
	"AttributeAgilityGain"		"2.500000"
	"MovementSpeed"		"300"
	"MovementTurnRate"		"0.400000"

}