"npc_dota_hero_witch_doctor"
{
	"ArmorPhysical"		"0"
	"AttackCapabilities"		"DOTA_UNIT_CAP_RANGED_ATTACK"
	"AttackDamageMin"		"27"
	"AttackDamageMax"		"37"
	"AttackRate"		"1.7"

	"AttributePrimary"		"DOTA_ATTRIBUTE_INTELLECT"
	"AttributeBaseStrength"		"16"
	"AttributeStrengthGain"		"2.200000"
	"AttributeBaseIntelligence"		"24"
	"AttributeIntelligenceGain"		"3.200000"
	"AttributeBaseAgility"		"13"
	"AttributeAgilityGain"		"2.000000"
	"MovementSpeed"		"305"
	"MovementTurnRate"		"0.400000"

}