megacreep_ancient_golem_fire_fist = class({})
LinkLuaModifier("modifier_megacreep_ancient_golem_fire_fist", "creeps/abilities/megacreep_golem/modifiers/modifier_megacreep_ancient_golem_fire_fist", LUA_MODIFIER_MOTION_NONE)

function megacreep_ancient_golem_fire_fist:GetIntrinsicModifierName()
	return "modifier_megacreep_ancient_golem_fire_fist"
end