"gun_joe_special_bonus_rapid_cd"
{
	"BaseClass"						"special_bonus_unique_earth_spirit"
	"AbilityType"					"DOTA_ABILITY_TYPE_ATTRIBUTES"
	"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		
	// Special
	//-------------------------------------------------------------------------------------------------------------
	"AbilitySpecial"
	{
		"01"
		{
			"var_type"					"FIELD_INTEGER"
			"value"						"-2"
		}
	}
}

"gun_joe_special_bonus_explosive_bullets_cd"
{
	"BaseClass"						"special_bonus_unique_earth_spirit"
	"AbilityType"					"DOTA_ABILITY_TYPE_ATTRIBUTES"
	"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		
	// Special
	//-------------------------------------------------------------------------------------------------------------
	"AbilitySpecial"
	{
		"01"
		{
			"var_type"					"FIELD_INTEGER"
			"value"				"-8"
		}
	}
}

"gun_joe_special_bonus_explosive_bullets_stack"
{
	"BaseClass"						"special_bonus_unique_earth_spirit"
	"AbilityType"					"DOTA_ABILITY_TYPE_ATTRIBUTES"
	"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		
	// Special
	//-------------------------------------------------------------------------------------------------------------
	"AbilitySpecial"
	{
		"01"
		{
			"var_type"					"FIELD_INTEGER"
			"value"				"4"
		}
	}
}

"gun_joe_special_bonus_explosive_bullets_radius"
{
	"BaseClass"						"special_bonus_unique_earth_spirit"
	"AbilityType"					"DOTA_ABILITY_TYPE_ATTRIBUTES"
	"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		
	// Special
	//-------------------------------------------------------------------------------------------------------------
	"AbilitySpecial"
	{
		"01"
		{
			"var_type"					"FIELD_INTEGER"
			"value"						"200"
		}
	}
}