"item_black_powder_bag"
{
	// General
	//-------------------------------------------------------------------------------------------------------------
	"ID"							"834"														// unique ID number for this item.  Do not change this once established or it will invalidate collected stats.
	"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE"
			
	// Item Info
	//-------------------------------------------------------------------------------------------------------------
	"ItemCost"						"0"
	"ItemIsNeutralDrop"				"1"
	"ItemPurchasable"				"0"

    // Stats
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCooldown"				"20"


	"Model"							"models/props_gameplay/neutral_box.vmdl"
		
	// Special	
	//-------------------------------------------------------------------------------------------------------------
	"AbilitySpecial"
	{
		"01"
		{
			"var_type"				"FIELD_INTEGER"
			"bonus_armor"			"12" // 7
		}
		"02"
		{
			"var_type"				"FIELD_INTEGER"
			"radius"				"300"
		}
		"03"
		{
			"var_type"				"FIELD_INTEGER"
			"damage"				"300"
		}
		"04"
		{
			"var_type"				"FIELD_FLOAT"
			"blind_duration"			"2"
		}
		"05"
		{
			"var_type"				"FIELD_INTEGER"
			"blind_pct"			"100"
		}
    }	
}