"item_arcane_boots"
{
	// Special	
	//-------------------------------------------------------------------------------------------------------------
	"AbilitySpecial"
	{
		"01"
		{
			"var_type"				"FIELD_INTEGER"
			"bonus_movement"		"45"
		}
		"02"
		{
			"var_type"				"FIELD_INTEGER"
			"bonus_mana"			"250"
		}			
		"03"
		{
			"var_type"				"FIELD_INTEGER"
			"replenish_amount"		"280"
		}
		"04"
		{
			"var_type"				"FIELD_INTEGER"
			"replenish_radius"		"1200"
		}
	}
}