"item_faerie_fire"
{
	// Stats
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCastPoint"				"0.0"
	"AbilityCooldown"				"5.0"

	// Special	
	//-------------------------------------------------------------------------------------------------------------
	"AbilitySpecial"
	{
		"01"
		{
			"var_type"				"FIELD_INTEGER"
			"bonus_damage"			"5"
		}
		"02"
		{
			"var_type"				"FIELD_INTEGER"
			"hp_restore"			"150"
		}
	}
}