"item_tango"
{
	"AbilitySpecial"
	{
		"01"
		{
			"var_type"				"FIELD_FLOAT"
			"health_regen"			"17.0"
		}
		"02"
		{
			"var_type"				"FIELD_FLOAT"
			"buff_duration"			"10.0"
		}
		"03"
		{
			"var_type"				"FIELD_INTEGER"
			"tooltip_charges"				"3"
		}
	}
}

"item_tango_single"
{
	"AbilitySpecial"
	{
		"01"
		{
			"var_type"				"FIELD_FLOAT"
			"health_regen"			"17.0"
		}
		"02"
		{
			"var_type"				"FIELD_FLOAT"
			"buff_duration"			"10.0"
		}
	}
}