//=================================================================================================================
// Hoodwink: Acorn Shot
//=================================================================================================================
"hoodwink_acorn_shot"
{
	// General
	//-------------------------------------------------------------------------------------------------------------
	
	"MaxLevel"						"7"

	// Time		
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCooldown"				"16 15 14 13 12 11 10"
	"AbilityCastRange"				"575"
	"AbilityCastPoint"				"0.2"
	"AbilityManaCost"				"75 85 95 105 115 125 135"

	// Special
	//-------------------------------------------------------------------------------------------------------------
	"AbilitySpecial"
	{		
		"01"
		{	
			"var_type"				"FIELD_INTEGER"
			"bonus_range"			"125 200 275 325 350 375 400"
		}
		"02"
		{	
			"var_type"				"FIELD_INTEGER"
			"acorn_shot_damage"		"50 75 100 125 150 175 200"
		}
		"03"
		{	
			"var_type"				"FIELD_INTEGER"
			"base_damage_pct"		"25 30 35 40 45 50 55"
		}
		"04"
		{	
			"var_type"				"FIELD_INTEGER"
			"bounce_count"			"3 4 5 6 7 8 9"
			"LinkedSpecialBonus"	"special_bonus_unique_hoodwink_sharpshooter_speed"
		}
		"05"
		{	
			"var_type"				"FIELD_INTEGER"
			"bounce_range"			"525"
		}
		"06"
		{
			"var_type"				"FIELD_FLOAT"
			"debuff_duration"		"0.25"
		}
		"07"
		{	
			"var_type"				"FIELD_INTEGER"
			"slow"					"100"
		}
		"08"
		{
			"var_type"				"FIELD_FLOAT"
			"bounce_delay"			"0.1"
		}
	}
	"AbilityCastAnimation"		"ACT_DOTA_CAST_ABILITY_1"
}

//=================================================================================================================
// Hoodwink: Bushwhack
//=================================================================================================================
"hoodwink_bushwhack"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"ID"							"8158"														// unique ID number for this ability.  Do not change this once established or it will invalidate collected stats.
		
		"MaxLevel"						"7"

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"1200"
		"AbilityCastPoint"				"0.2"
		"AbilityCastAnimation"			"ACT_DOTA_CAST_ABILITY_2"
		
		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"14"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"90 100 110 120 130 140 150"
		
		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
		{
			"trap_radius"		
			{
				"value"		"325"
				"special_bonus_unique_hoodwink_bushwhack_radius"	"+135"
			}
			"debuff_duration"		"1.3 1.6 1.9 2.2 2.3 2.4 2.5"
			"projectile_speed"	"1000"
			"total_damage"		"110 180 270 360 420 520 600"
			"animation_rate"	"0.3"
			"visual_height"		"50"
		}
	}


//=================================================================================================================
// Hoodwink: Scurry
//=================================================================================================================
"hoodwink_scurry"
{
	// General
	//-------------------------------------------------------------------------------------------------------------
	
	"MaxLevel"						"7"
	
	// Casting
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCastPoint"				"0.0"
	"AbilityCastRange"				"275"
	
	// Time		
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCooldown"				"0.0"
	"AbilityCharges"				"2"
	"AbilityChargeRestoreTime"		"30 27 25 22 20 17 15"
	
	// Cost
	//-------------------------------------------------------------------------------------------------------------
	"AbilityManaCost"				"35"
	
	// Special
	//-------------------------------------------------------------------------------------------------------------
	"AbilityValues"
		{
			"radius"						"275"
			"movement_speed_pct"			"25 30 35 40 45 50 55"
			"duration"						"4.0"
			"evasion"						"16 20 24 28 32 36 40"
			"bonus_active_evasion"
			{
				"value"			"0"
				"special_bonus_unique_hoodwink_scurry_evasion"			"+40"
			}
			"decoy_duration"					"6.0"
			"decoy_detonate_radius"				"250"
			"decoy_stun_duration"				"2.0"
			"images_do_damage_percent"			"0"
			"images_take_damage_percent"		"100"
			"projectile_speed"					"1200"
			"movement_speed"					"15"


		}
		"AbilityCastAnimation"		"ACT_DOTA_CAST_ABILITY_3"
	}

//=================================================================================================================
// Hoodwink: Sharpshooter
//=================================================================================================================
"hoodwink_sharpshooter"
{
	// General
	//-------------------------------------------------------------------------------------------------------------
	
	"MaxLevel"						"7"
	
	
	// Casting
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCastRange"				"3000"
	"AbilityCastPoint"				"0.0"

	// Time		
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCooldown"				"25"

	// Cost
	//-------------------------------------------------------------------------------------------------------------
	"AbilityManaCost"				"150"

	// Special
	//-------------------------------------------------------------------------------------------------------------
	"AbilitySpecial"
	{
		"01"
		{
			"var_type"			"FIELD_FLOAT"
			"arrow_speed"		"2200"
		}
		"02"
		{
			"var_type"			"FIELD_INTEGER"
			"arrow_width"		"125"
		}
		"03"
		{
			"var_type"			"FIELD_INTEGER"
			"arrow_range"		"3000"
		}
		"04"
		{
			"var_type"			"FIELD_INTEGER"
			"arrow_vision"		"350"
		}
		"05"
		{
			"var_type"					"FIELD_FLOAT"
			"max_charge_time"			"2.0"
			"LinkedSpecialBonus"		"special_bonus_unique_hoodwink_sharpshooter_speed"
		}			
		"06"
		{
			"var_type"					"FIELD_INTEGER"
			"max_damage"				"700 800 900 1000 1200 1600 2500"
		}
		"07"
		{
			"var_type"					"FIELD_INTEGER"
			"recoil_distance"			"350"
		}
		"08"
		{
			"var_type"					"FIELD_INTEGER"
			"recoil_height"				"75"
		}
		"09"
		{
			"var_type"					"FIELD_FLOAT"
			"recoil_duration"			"0.4"
		}
		"10"
		{
			"var_type"					"FIELD_FLOAT"
			"max_slow_debuff_duration"	"6.0"
		}
		"11"
		{
			"var_type"					"FIELD_FLOAT"
			"misfire_time"				"5.0"
		}
		"12"
		{
			"var_type"					"FIELD_INTEGER"
			"slow_move_pct"				"50"
		}
		"13"
		{
			"var_type"					"FIELD_FLOAT"
			"turn_rate"					"60"
		}
		"14"
		{
			"var_type"					"FIELD_FLOAT"
			"base_power"				"0.2"
		}
	}
	"AbilityCastAnimation"		"ACT_DOTA_CHANNEL_ABILITY_6"
}


//=================================================================================================================
// Ability: Hoodwink: Hunter's Boomerang
//=================================================================================================================
"hoodwink_hunters_boomerang"
{
	// General
	//-------------------------------------------------------------------------------------------------------------
	

	// Casting
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCastRange"				"1000"
	"AbilityCastPoint"				"0.2"
	
	// Time		
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCooldown"				"13"

	// Cost
	//-------------------------------------------------------------------------------------------------------------
	"AbilityManaCost"				"175"

	// Special
	//-------------------------------------------------------------------------------------------------------------
	"AbilitySpecial"
	{
		"01"
		{
			"var_type"				"FIELD_INTEGER"
			"speed"					"900"
		}
		"02"
		{
			"var_type"				"FIELD_INTEGER"
			"radius"				"150"
		}
		"03"
		{
			"var_type"				"FIELD_INTEGER"
			"damage"				"450"
		}
		"04"
		{
			"var_type"				"FIELD_FLOAT"
			"mark_duration"			"7.0"
		}
		"05"
		{
			"var_type"				"FIELD_INTEGER"
			"slow_pct"				"20"
		}
		"06"
		{
			"var_type"				"FIELD_INTEGER"
			"spell_amp"				"25"
		}
		"07"
		{
			"var_type"				"FIELD_INTEGER"
			"status_resistance"		"25"
		}
		"08"
		{
			"var_type"				"FIELD_INTEGER"
			"spread"				"400"
		}
		"09"
		{
			"var_type"				"FIELD_FLOAT"
			"min_throw_duration"			"0.5"
		}
		"10"
		{
			"var_type"				"FIELD_FLOAT"
			"max_throw_duration"			"1.2"
		}
	}
	"AbilityCastAnimation"		"ACT_DOTA_CAST_ABILITY_2"
}

//=================================================================================================================
// Hoodwink: Decoy
//=================================================================================================================
"hoodwink_decoy"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"ID"							"8107"														// unique ID number for this ability.  Do not change this once established or it will invalidate collected stats.
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastPoint"				"0"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"20.0"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"60"
		
		// Cast Range
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"0"

		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
		{
			"duration"					"12.0"
			"decoy_detonate_radius"		"250"
			"decoy_stun_duration"				"1.0"
			"images_do_damage_percent"	"100"
			"images_take_damage_percent"	"100"
			"projectile_speed"	"1200"
			"movement_speed"				"15"
			"sharpshooter_damage_pct"			"60"

		}
	}
