//=================================================================================================================
	// Ability: Snapfire Scatterblast
	//=================================================================================================================
	"snapfire_scatterblast"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"ID"							"6480"	// unique ID number for this ability.  Do not change this once established or it will invalidate collected stats.
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"	
		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_NO"
		"FightRecapLevel"				"1"
		"AbilitySound"					"Hero_Snapfire.Shotgun.Fire"

	    "HasShardUpgrade"               "1"
	    "MaxLevel" "7"

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"800"
		"AbilityCastPoint"				"0.4"
		"AbilityCastAnimation"			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate"			"1.2" // 1.0 corresponds to cast point of 0.45 or so

		// Time
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"10"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"80 90 100 110 130 140 150"

		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"					"FIELD_INTEGER"
				"damage"					"150 225 300 350 400 425 500"
				"LinkedSpecialBonus"		"special_bonus_unique_snapfire_7"
			}
			"02"
			{
				"var_type"					"FIELD_INTEGER"
				"blast_speed"				"3000"
			}
			"03"
			{
				"var_type"					"FIELD_INTEGER"
				"blast_width_initial"		"225"
			}
			"04"
			{
				"var_type"					"FIELD_INTEGER"
				"blast_width_end"			"400"
			}
			"05"
			{
				"var_type"					"FIELD_FLOAT"
				"debuff_duration"			"1.0"
				"LinkedSpecialBonus"		"special_bonus_unique_snapfire_2"
			}
			"06"
			{
				"var_type"					"FIELD_INTEGER"
				"movement_slow_pct"			"100"
			}
			"07"
			{
				"var_type"					"FIELD_INTEGER"
				"attack_slow_pct"			"100"
			}
			"08"
			{
				"var_type"					"FIELD_INTEGER"
				"point_blank_range"			"450"
			}
			"09"
			{
				"var_type"					"FIELD_FLOAT"
				"point_blank_dmg_bonus_pct"	"50.0"
			}
			"10"
			{
				"var_type"					"FIELD_INTEGER"
				"shard_knockback_distance"			"250"
				"RequiresShard"				"1"
			}
			"11"
			{
				"var_type"					"FIELD_FLOAT"
				"shard_knockback_duration"			"0.3"
				"RequiresShard"				"1"
			}
			"12"
			{
				"var_type"					"FIELD_FLOAT"
				"shard_stun_duration"			"1.4"
				"RequiresShard"				"1"
				
			}
			"13"
			{
				"var_type"					"FIELD_FLOAT"
				"shard_bonus_point_blank_dmg_pct"			"85.0"
				"RequiresShard"				"1"
				
			}
		}
	}

	//=================================================================================================================
	// Ability: Snapfire Mortimer Kisses
	//=================================================================================================================
	"snapfire_mortimer_kisses"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"ID"							"6482"	// unique ID number for this ability.  Do not change this once established or it will invalidate collected stats.
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_DONT_RESUME_MOVEMENT | DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK"
		"AbilityType"					"DOTA_ABILITY_TYPE_ULTIMATE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_NO"
		"SpellDispellableType"			"SPELL_DISPELLABLE_YES"
		"AbilitySound"					"Hero_Snapfire.MortimerBlob.Launch"

		// Gobble up scepter ability not tied to any spell in regular game, for AD, associating it here.
		"AbilityDraftUltScepterAbility" "snapfire_gobble_up"
		"AbilityDraftUltScepterPreAbility" "snapfire_spit_creep"
		"MaxLevel" "7"

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"3000"
		"AbilityCastPoint"				"0.5"
		"AbilityCastAnimation"			"ACT_DOTA_CAST_ABILITY_4"

		// Damage
		//-------------------------------------------------------------------------------------------------------------
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"65"
		"AbilityDuration"				"6"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"125 150 175 195 220 245"

		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"				"FIELD_INTEGER"
				"projectile_count"		"8"
				"LinkedSpecialBonus"	"special_bonus_unique_snapfire_1"
			}
			"02"
			{
				"var_type"				"FIELD_INTEGER"
				"projectile_speed"		"1300"
			}
			"03"
			{
				"var_type"				"FIELD_INTEGER"
				"projectile_width"		"130"
			}
			"04"
			{
				"var_type"				"FIELD_INTEGER"
				"impact_radius"			"275"
			}
			"05"
			{
				"var_type"				"FIELD_INTEGER"
				"damage_per_impact"		"300 400 500 600 700 800 900"
			}
			"06"
			{
				"var_type"				"FIELD_FLOAT"
				"duration_tooltip"		"6"
			}
			"07"
			{
				"var_type"				"FIELD_INTEGER"
				"projectile_vision"		"500"
			}
			"08"
			{
				"var_type"				"FIELD_FLOAT"
				"turn_rate"				"75"
			}
			"09"
			{
				"var_type"				"FIELD_FLOAT"
				"burn_interval"			"0.5"
			}
			"10"
			{
				"var_type"				"FIELD_INTEGER"
				"burn_damage"			"100 150 200 250 300 350 400"
			}
			"11"
			{
				"var_type"				"FIELD_INTEGER"
				"move_slow_pct"			"25"
				"LinkedSpecialBonus"	"special_bonus_unique_snapfire_4"
			}
			"12"
			{
				"var_type"				"FIELD_FLOAT"
				"burn_ground_duration"	"3.0"
			}
			"13"
			{
				"var_type"				"FIELD_FLOAT"
				"dist_change_speed"		"75"
			}
			"14"
			{
				"var_type"				"FIELD_INTEGER"
				"min_range"				"600"
			}
			"15"
			{
				"var_type"				"FIELD_FLOAT"
				"min_lob_travel_time"	"0.8"
			}
			"16"
			{
				"var_type"				"FIELD_FLOAT"
				"max_lob_travel_time"	"2.0"
			}
			"17"
			{
				"var_type"						"FIELD_FLOAT"
				"delay_after_last_projectile"	"0.5"
			}
			"18"
			{
				"var_type"				"FIELD_FLOAT"
				"burn_linger_duration"	"1.0"
			}
		}
	}

	//=================================================================================================================
	// Snapfire: Gobble Up
	//=================================================================================================================
	"snapfire_gobble_up"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"ID"							"6484"	// unique ID number for this ability.  Do not change this once established or it will invalidate collected stats.
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK | DOTA_ABILITY_BEHAVIOR_HIDDEN | DOTA_ABILITY_BEHAVIOR_SHOW_IN_GUIDES"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_CUSTOM"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_CUSTOM"
		"MaxLevel"						"1"
		"FightRecapLevel"				"1"
		"IsGrantedByScepter"			"1"
		"HasScepterUpgrade"				"1"
		"AbilitySound"					"Hero_Snapfire.GobbleUp.Cast"

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastPoint"				"0.3"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"120"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"150"
		"AbilityCooldown"				"40"

		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"				"FIELD_FLOAT"
				"max_time_in_belly"		"3.0"
				"RequiresScepter"		"1"
			}
		}
		"AbilityCastAnimation"		"ACT_DOTA_CAST_ABILITY_1"
	}

	//=================================================================================================================
	// Snapfire Spit Creep
	//=================================================================================================================
	"snapfire_spit_creep"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"ID"							"6486"	// unique ID number for this ability.  Do not change this once established or it will invalidate collected stats.
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_DONT_RESUME_MOVEMENT | DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_NO"
		"SpellDispellableType"			"SPELL_DISPELLABLE_YES"
		"MaxLevel"						"1"
		"FightRecapLevel"				"1"
		"IsGrantedByScepter"			"1"
		"AbilitySound"					"Hero_Snapfire.MortimerBlob.Launch"

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"3000"
		"AbilityCastPoint"				"0.3"
		"AbilityCastAnimation"			"ACT_DOTA_CAST_ABILITY_4"

		// Damage
		//-------------------------------------------------------------------------------------------------------------
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"0"

		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"				"FIELD_INTEGER"
				"projectile_speed"		"1400"
			}
			"02"
			{
				"var_type"				"FIELD_INTEGER"
				"projectile_width"		"130"
			}
			"03"
			{
				"var_type"				"FIELD_INTEGER"
				"impact_radius"			"400"
			}
			"05"
			{
				"var_type"				"FIELD_INTEGER"
				"projectile_vision"		"500"
			}
			"06"
			{
				"var_type"				"FIELD_FLOAT"
				"burn_interval"			"0.5"
			}
			"07"
			{
				"var_type"				"FIELD_INTEGER"
				"burn_damage"			"100"
			}
			"08"
			{
				"var_type"				"FIELD_INTEGER"
				"move_slow_pct"			"25"
				"LinkedSpecialBonus"	"special_bonus_unique_snapfire_4"
			}
			"09"
			{
				"var_type"				"FIELD_FLOAT"
				"burn_ground_duration"	"3.0"
			}
			"10"
			{
				"var_type"				"FIELD_INTEGER"
				"min_range"				"0" //"600"
			}
			"11"
			{
				"var_type"				"FIELD_FLOAT"
				"min_lob_travel_time"	"0.1"
			}
			"12"
			{
				"var_type"				"FIELD_FLOAT"
				"max_lob_travel_time"	"2.0"
			}
			"13"
			{
				"var_type"				"FIELD_FLOAT"
				"burn_linger_duration"	"1.0"
			}
			"14"
			{
				"var_type"				"FIELD_FLOAT"
				"stun_duration"			"1.5"
			}
			"15"
			{
				"var_type"					"FIELD_FLOAT"
				"min_height_above_lowest"	"150.0"
			}
			"16"
			{
				"var_type"					"FIELD_FLOAT"
				"min_height_above_highest"	"100.0"
			}
			"17"
			{
				"var_type"				"FIELD_FLOAT"
				"min_acceleration"		"1000.0"
			}
			"18"
			{
				"var_type"				"FIELD_FLOAT"
				"max_acceleration"		"2000.0"
			}
		}
	}

	//=================================================================================================================
	// Ability: Snapfire Firesnap Cookie
	//=================================================================================================================
	"snapfire_firesnap_cookie"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"ID"							"6483"	// unique ID number for this ability.  Do not change this once established or it will invalidate collected stats.
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_FRIENDLY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_CREEP"
		"SpellDispellableType"			"SPELL_DISPELLABLE_YES_STRONG"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"FightRecapLevel"				"1"
		"AbilitySound"					"Hero_Snapfire.FeedCookie.Cast"
		"MaxLevel" "7"

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"700"
		"AbilityCastPoint"				"0.2"
		"AbilityCastAnimation"			"ACT_DOTA_CAST_ABILITY_2"

		// Time
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"18 17 16 15 14 13 12"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"100"

		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
		{
				"projectile_speed"		"800"
				"pre_hop_duration"		"0.0"
				"jump_duration"			"0.484" //"0.431 0.484 0.538 0.592" // proportional to horizontal distance
				"jump_height"			"257" //"228 257 285 314" // proportional to horizontal distance
				"jump_horizontal_distance"	"425" //"400 450 500 550"
				"pre_land_anim_time"	"0.14"
				"landing_gesture_duration"	"0.6"
				"impact_radius"			"300"
				"impact_damage"			"90 160 230 300 400 500 600"
				"impact_stun_duration"	
				{
					"value"		"1.6 1.8 2.1 2.3 2.5 2.8 3.0"
					"special_bonus_unique_snapfire_3"	"+0.3"

				}
				"self_cast_delay"		"0.4"
				"target_heal"			
				{
					"value"			"0"
					"special_bonus_unique_snapfire_5"	"+125"
				}
		}
	}

	//=================================================================================================================
	// Ability: Snapfire Lil Shredder
	//=================================================================================================================
	"snapfire_lil_shredder"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"ID"							"6488"	// unique ID number for this ability.  Do not change this once established or it will invalidate collected stats.
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_PHYSICAL"
		"FightRecapLevel"				"1"
		"AbilitySound"					"Hero_Snapfire.ExplosiveShells.Cast"
		"MaxLevel" "7"

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastPoint"				"0.0"
		"AbilityCastRange"				"800"
		"AbilityCastAnimation"			"ACT_DOTA_OVERRIDE_ABILITY_3"

		// Time
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"16 15 14 13 12 11 10"
		"AbilityDuration"				"8"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"75"
		
		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
		{
				"damage"					"45 60 75 90 110 130 140"
				"buffed_attacks"			
				{
					"value"		"6"
					"special_bonus_unique_snapfire_2"	"+2"
				}
				"attack_speed_bonus"		"300"
				"attack_range_bonus"		"75 150 225 300 325 450 500"
				"buff_duration_tooltip"		"8"
				"base_attack_time"			"1.0"
				"armor_reduction_per_attack"	"0.5"
				"armor_duration"				"4.0"
		}
	}