//=================================================================================================================
	// Spectre: Spectral Dagger
	//=================================================================================================================
	"spectre_spectral_dagger"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"ID"							"5334"														// unique ID number for this ability.  Do not change this once established or it will invalidate collected stats.
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO"
		"AbilityUnitTargetFlags"		"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_YES"
		"SpellDispellableType"			"SPELL_DISPELLABLE_YES"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"FightRecapLevel"				"1"
		"AbilitySound"					"Hero_Spectre.DaggerCast"
		"MaxLevel"						"7"

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"2000"
		"AbilityCastPoint"				"0.3"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"20 19 18 17 16 16 16" // 16

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"45 50 55 60 65 70 75"

		// Stats
		//-------------------------------------------------------------------------------------------------------------
		"AbilityModifierSupportValue"	"0.0"	// Modifier has no support value

		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"				"FIELD_INTEGER"
				"damage"				"100 166 233 300 366 433 500"
				"LinkedSpecialBonus"		"special_bonus_unique_spectre_6"
			}
			"02"
			{
				"var_type"				"FIELD_INTEGER"
				"bonus_movespeed"		"8 12 16 20 26 28 30"

				"LinkedSpecialBonus"		"special_bonus_unique_spectre_3"
			}
			"03"
			{
				"var_type"				"FIELD_FLOAT"
				"dagger_path_duration"	"12"
			}
			"04"
			{
				"var_type"				"FIELD_FLOAT"
				"hero_path_duration"	"7.0"
			}
			"05"	
			{
				"var_type"				"FIELD_FLOAT"
				"buff_persistence"		"4.0"
			}
			"08"
			{
				"var_type"				"FIELD_INTEGER"
				"dagger_radius"			"125"
			}
			"09"
			{
				"var_type"				"FIELD_INTEGER"
				"path_radius"			"175"
			}
			"10"
			{
				"var_type"				"FIELD_INTEGER"
				"vision_radius"			"200"
			}
			"11"
			{
				"var_type"				"FIELD_INTEGER"
				"speed"					"800"
			}
			"12"
			{
				"var_type"				"FIELD_FLOAT"
				"dagger_grace_period"	"2.0" // 4
			}
		}
		"AbilityCastAnimation"		"ACT_DOTA_CAST_ABILITY_1"
	}

	//=================================================================================================================
	// Spectre: Desolate
	//=================================================================================================================
	"spectre_desolate"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"ID"							"5335"														// unique ID number for this ability.  Do not change this once established or it will invalidate collected stats.
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_PURE"
		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_YES"
		"AbilitySound"					"Hero_Spectre.Desolate"
		"MaxLevel"						"7"

		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"				"FIELD_INTEGER"
				"bonus_damage"			"25 35 45 55 65 75 85"
				"LinkedSpecialBonus"		"special_bonus_unique_spectre_2"
			}
			"02"
			{
				"var_type"				"FIELD_INTEGER"
				"radius"				"325"
			}
		}
		"AbilityCastAnimation"		"ACT_DOTA_CAST_ABILITY_2"
	}

	//=================================================================================================================
	// Spectre: Dispersion
	//=================================================================================================================
	"spectre_dispersion"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"ID"							"5336"														// unique ID number for this ability.  Do not change this once established or it will invalidate collected stats.
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_YES"
        "HasShardUpgrade"               "1"
        "MaxLevel"						"7"


		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"				"FIELD_INTEGER"
				"damage_reflection_pct"	"14 15 16 17 18 19 20"
				"LinkedSpecialBonus"		"special_bonus_unique_spectre_5"
			}
			"02"
			{
				"var_type"				"FIELD_INTEGER"
				"min_radius"			"300"
			}
			"03"
			{
				"var_type"				"FIELD_INTEGER"
				"max_radius"			"600"
			}	
			"04"
			{
				"var_type"				"FIELD_INTEGER"
				"shard_dagger_damage"			"300"
				"RequiresShard"			"1"
			}	
			"05"
			{
				"var_type"						"FIELD_FLOAT"
				"shard_dagger_cooldown"			"7.0"
				"RequiresShard"					"1"
			}		
		}
		"AbilityCastAnimation"		"ACT_DOTA_CAST_ABILITY_3"
	}

	//=================================================================================================================
	// Spectre: Haunt
	//=================================================================================================================
	"spectre_haunt"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"ID"							"5337"														// unique ID number for this ability.  Do not change this once established or it will invalidate collected stats.
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityType"					"DOTA_ABILITY_TYPE_ULTIMATE"
		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_YES"
		"FightRecapLevel"				"2"
		"AbilitySound"					"Hero_Spectre.Haunt"

		"HasScepterUpgrade"			"1"
		"AbilityDraftPreAbility"		"spectre_reality"
		"AbilityDraftUltScepterAbility"		"spectre_haunt_single"
		"MaxLevel"						"7"

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastPoint"				"0.3"
		"AbilityCastAnimation"			"ACT_DOTA_CAST_ABILITY_4"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"100"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"150 200 300 400 500 600 700"

		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"					"FIELD_FLOAT"
				"duration"					"5.0 5.5 6.0 6.5 7.0 7.5 8.0"
			}
			"02"
			{
				"var_type"					"FIELD_INTEGER"
				"illusion_damage_outgoing"	"-60"
			}
			"03"
			{
				"var_type"					"FIELD_INTEGER"
				"tooltip_outgoing"	"40"
				"LinkedSpecialBonus"		"special_bonus_unique_spectre_4"
			}
			"04"
			{
				"var_type"					"FIELD_INTEGER"
				"illusion_damage_incoming"	"250"
			}
			"05"
			{
				"var_type"					"FIELD_INTEGER"
				"tooltip_illusion_total_damage_incoming"	"350"
			}			
			"06"
			{
				"var_type"					"FIELD_FLOAT"
				"attack_delay"				"1"
			}			
		}
	}

	//=================================================================================================================
	// Spectre: Haunt Single
	//=================================================================================================================
	"spectre_haunt_single"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"ID"							"7851"														// unique ID number for this ability.  Do not change this once established or it will invalidate collected stats.
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN | DOTA_ABILITY_BEHAVIOR_SHOW_IN_GUIDES | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO"
		"AbilityUnitTargetFlags"		"DOTA_UNIT_TARGET_FLAG_NOT_CREEP_HERO | DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_YES"
		"FightRecapLevel"				"2"
		"MaxLevel"						"3"
		"AbilitySound"					"Hero_Spectre.Haunt"
		"HasScepterUpgrade"			"1"

		"IsGrantedByScepter"			"1"
		"AbilityDraftPreAbility"		"spectre_reality"
		"MaxLevel"						"7"

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastPoint"				"0.3"
		"AbilityCastAnimation"			"ACT_DOTA_CAST_ABILITY_4"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"45"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"180"

		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"					"FIELD_FLOAT"
				"duration"					"7.0"
				"RequiresScepter"			"1"
			}
			"02"
			{
				"var_type"					"FIELD_INTEGER"
				"illusion_damage_outgoing"	"-60"
				"RequiresScepter"			"1"
			}
			"03"
			{
				"var_type"					"FIELD_INTEGER"
				"tooltip_outgoing"	"40"
				"LinkedSpecialBonus"		"special_bonus_unique_spectre_4"
				"RequiresScepter"			"1"
			}
			"04"
			{
				"var_type"					"FIELD_INTEGER"
				"illusion_damage_incoming"	"150"
				"RequiresScepter"			"1"
			}
			"05"
			{
				"var_type"					"FIELD_INTEGER"
				"tooltip_illusion_total_damage_incoming"	"250"
				"RequiresScepter"			"1"
			}			
			"06"
			{
				"var_type"					"FIELD_FLOAT"
				"attack_delay"				"1"
				"RequiresScepter"			"1"
			}						
		}
	}

	//=================================================================================================================
	// Spectre: Reality
	//=================================================================================================================
	"spectre_reality"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"ID"							"5338"														// unique ID number for this ability.  Do not change this once established or it will invalidate collected stats.
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE | DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityType"					"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"						"1"
		"AbilityCastAnimation"			"ACT_DOTA_CAST_ABILITY_5"
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastPoint"				"0"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"0"
	}