//=================================================================================================================
	// Techies: Land Mines
	//=================================================================================================================
	"techies_land_mines"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"ID"							"5599"														// unique ID number for this ability.  Do not change this once established or it will invalidate collected stats.
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_NO"
		"HasScepterUpgrade"				"1"
		"AbilityType"					"DOTA_ABILITY_TYPE_ULTIMATE"
		"MaxLevel"						"7"


		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"400"
		"AbilityCastPoint"				"0.0 0.0 0.0 0.0"
		
		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"0"
		"AbilityCharges"				"8" // 3
	
		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"110 140 170 200 230 260 290"

		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
		{
				"radius"				"500"
				"proximity_threshold"				"1.0"
				"damage"					
				{
					"value"			"350 450 550 660 750 850 950" //"200 300 400 500 575 625 675"
					"LinkedSpecialBonus"		"special_bonus_unique_techies_2"
				}
				"building_damage_pct"		"30"
				"activation_delay"			
				{
					"value"		"1"
					"special_bonus_unique_techies_4"	"-0.8"
				}
				"cast_range_scepter_bonus"		
				{
					"value"		"300"
					"RequiresScepter"			"1"
				}
				"AbilityChargeRestoreTime"
				{
					"value"		"15" 
					"special_bonus_unique_techies_3"	"-3"
				}
				"outer_damage"				"50"
				"min_distance"				"150"
				"placement_radius"			"350"
				"mres_reduction"			"15 20 25"
				"burn_duration"				"5"
		}
		"AbilityCastAnimation"		"ACT_DOTA_CAST_ABILITY_1"
	}

	//=================================================================================================================
	// Techies: Stasis Trap
	//=================================================================================================================
	"techies_stasis_trap"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"ID"							"5600"														// unique ID number for this ability.  Do not change this once established or it will invalidate collected stats.
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_NORMAL_WHEN_STOLEN | DOTA_ABILITY_BEHAVIOR_AOE"
		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_NO"
		"SpellDispellableType"			"SPELL_DISPELLABLE_YES"
		"HasScepterUpgrade"				"1"

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"150"
		"AbilityCastPoint"				"1.0"
		
		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"20.0 16.0 13.0 10.0"
	
		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"80 110 140 160"

		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilitySpecial"
		{		
			"01"
			{
				"var_type"					"FIELD_INTEGER"
				"activation_radius"			"400"
			}
			"02"
			{
				"var_type"					"FIELD_FLOAT"
				"explode_delay"			"0"
			}
			"03"
			{
				"var_type"					"FIELD_INTEGER"
				"stun_radius"				"600"
			}
			"04"
			{
				"var_type"					"FIELD_FLOAT"
				"stun_duration"				"2 3 4 5"
			}
			"05"
			{
				"var_type"					"FIELD_FLOAT"
				"activation_time"			"2.0"
			}	
			"06"
			{
				"var_type"					"FIELD_FLOAT"
				"fade_time"					"2.0"
			}		
			"07"
			{
				"var_type"					"FIELD_FLOAT"
				"duration"					"600.0"
			}
			"08"
			{
				"var_type"					"FIELD_INTEGER"
				"cast_range_scepter_bonus"		"300"
				"RequiresScepter"			"1"
			}	
		}
		"AbilityCastAnimation"		"ACT_DOTA_CAST_ABILITY_2"
	}

	//=================================================================================================================
	// Techies: Suicide Squad, Attack!
	//=================================================================================================================
	"techies_suicide"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"ID"							"5601"														// unique ID number for this ability.  Do not change this once established or it will invalidate collected stats.
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_NORMAL_WHEN_STOLEN | DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_NO"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"SpellDispellableType"			"SPELL_DISPELLABLE_YES"
		"FightRecapLevel"				"1"
        "HasShardUpgrade"               "1"
        "MaxLevel"						"7"

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"800"
		"AbilityCastPoint"				"1.0"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"25"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"175"

		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"					"FIELD_INTEGER"
				"radius"				"400"
			}
			"02"
			{
				"var_type"					"FIELD_INTEGER"
				"damage"					"200 250 300 350 400 450 500" //"200 300 400 500 550 600 650"
				"LinkedSpecialBonus"		"special_bonus_unique_techies"
			}
			"03"
			{
				"var_type"					"FIELD_FLOAT"
				"silence_duration"			"1 2 3 4 4 4 4"
			} 
			"04"
			{
				"var_type"					"FIELD_INTEGER"
				"hp_cost"			"35"
			} 
			"05"
			{
				"var_type"				"FIELD_FLOAT"
				"duration"				"0.75"
			}
			"06"
			{
				"var_type"				"FIELD_INTEGER"
				"shard_bonus_cast_range"				"300"
				"RequiresShard"			"1"
			}
			"06"
			{
				"var_type"				"FIELD_FLOAT"
				"shard_stun_duration"				"1.75"
				"RequiresShard"			"1"
			}							
		}
		"AbilityCastAnimation"		"ACT_DOTA_CAST_ABILITY_3"
	}


	//=================================================================================================================
	// Techies: Sticky Bomb
	//=================================================================================================================
	"techies_sticky_bomb"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"ID"					"879"														// unique ID number for this ability.  Do not change this once established or it will invalidate collected stats.
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"	
		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_NO"
		"FightRecapLevel"				"1"
		"AbilityCastAnimation"			"ACT_DOTA_CAST_ABILITY_6"
		"MaxLevel"						"7"

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"1000"
		"AbilityCastPoint"				"0.2"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"12 11 10 9 8 7 6"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				 "100 115 130 145 160 175 200" 

		// Stats
		//-------------------------------------------------------------------------------------------------------------
		"AbilityModifierSupportValue"	"0.25"	// generally used for damage only

		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
		{
				"duration"				"1.2"
				"countdown"				"2"
				"radius"				
				{
					"value"			"250"
					"special_bonus_unique_techies_2"	"+125"
				}
				"damage"				
				{
					"value"	"250 300 350 400 450 500 550" //"90 150 210 270 330 390 450"
				}
				"slow"					"25 30 35 40 45 50 55"
				"secondary_slow"		"15 20 25 30 35 40 45"
				"secondary_slow_duration"		"2.5"
				"explosion_radius"		
				{
					"value"				"300"
					"special_bonus_unique_techies_2"	"+125"
				}
				"speed"					"500.0"
				"acceleration"			"2000"
				"pre_chase_time"		"0.1"
		}
	}
	//=================================================================================================================
	// Techies: Reactive Taser
	//=================================================================================================================
	"techies_reactive_tazer"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"ID"					"886"														// unique ID number for this ability.  Do not change this once established or it will invalidate collected stats.
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_FRIENDLY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_CREEP"
		"FightRecapLevel"				"1"
		"AbilityCastAnimation"			"ACT_DOTA_CAST_ABILITY_2"
		"HasScepterUpgrade"				"1"
		"MaxLevel"						"7"
		// Casting
		//-------------------------------------------------------------------------------------------------------------		
		"AbilityCastPoint"				"0.1"
		"AbilityCastRange"				"500"
		

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"28 26 24 22 20 18 16"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"50 70 90 110 130 150 170"

		// Stats
		//-------------------------------------------------------------------------------------------------------------
		"AbilityModifierSupportValue"	"0.25"	// generally used for damage only

		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
		{
			"duration"				"6"
			"disarm_duration"		"2.4 2.55 2.7 2.85 3 3.15 3.3"
			"bonus_ms"				"15 20 25 30 35 40 45 55"
			"stun_radius"			"400"
			"scepter_damage"	
			{
				"value"					" 150 200 250 300 350 400 450 "
				"RequiresScepter"		"1"
			}	
		}
	}
	

	//=================================================================================================================
	// Techies: Remote Mines
	//=================================================================================================================
	"techies_remote_mines"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"ID"							"5602"														// unique ID number for this ability.  Do not change this once established or it will invalidate collected stats.
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_NORMAL_WHEN_STOLEN"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityType"					"DOTA_ABILITY_TYPE_ULTIMATE"
		"AbilityCastAnimation"			"ACT_DOTA_CAST_ABILITY_6"

		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_NO"
		"HasScepterUpgrade"				"1"
		"AbilityDraftPreAbility"		"techies_focused_detonate"

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"500"
		"AbilityCastPoint"				"0.75"
		
		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"8"
	
		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"120 180 240 300 360 420 480"

		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"					"FIELD_INTEGER"
				"max_mines"					"30"
			}
			"02"
			{
				"var_type"					"FIELD_INTEGER"
				"damage"					"300 375 450 525 600 675 750"
			}
			"03"
			{
				"var_type"					"FIELD_INTEGER"
				"radius"					"425"
			}		
			"04"
			{
				"var_type"					"FIELD_FLOAT"
				"duration"					"600.0"
			}
			"05"
			{
				"var_type"					"FIELD_FLOAT"
				"activation_time"			"1.7"
			}	
			"06"
			{
				"var_type"					"FIELD_INTEGER"
				"damage_scepter"			"450 525 600 675 750 825 900"
				"RequiresScepter"			"1"
			}
			"07"
			{
				"var_type"					"FIELD_INTEGER"
				"radius_scepter"			"425"
				"RequiresScepter"			"1"
			}
			"08"
			{
				"var_type"					"FIELD_INTEGER"
				"cast_range_scepter_bonus"		"300"
				"RequiresScepter"			"1"
			}			
			"09"
			{
				"var_type"					"FIELD_INTEGER"
				"vision_radius"			"500"
			}
			"10"
			{
				"var_type"					"FIELD_FLOAT"
				"vision_duration"			"3.0"
			}
			"11"
			{
				"var_type"					"FIELD_INTEGER"
				"model_scale"				"0 10 20"     // Percentage over model scale
			}
			"12"
			{
				"var_type"					"FIELD_FLOAT"
				"detonate_delay"			"0.25"
			}
		}
	}