//=================================================================================================================
// Techies: Land Mines
//=================================================================================================================
"techies_land_mines"
{
	"MaxLevel"						"7"

	// Casting
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCastRange"				"100"
	"AbilityCastPoint"				"0.0"
	
	// Time		
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCooldown"				"0"
	"AbilityCharges"				"2"
	"AbilityChargeRestoreTime"		"7"

	// Cost
	//-------------------------------------------------------------------------------------------------------------
	"AbilityManaCost"				"90 100 110 120 130 140 150"

	// Special
	//-------------------------------------------------------------------------------------------------------------
	"AbilitySpecial"
	{
		"01"
		{
			"var_type"					"FIELD_INTEGER"
			"radius"					"400"
		}
		"02"
		{
			"var_type"					"FIELD_FLOAT"
			"proximity_threshold"		"1.4 1.35 1.32 1.3 1.28 1.26 1.25"
		}
		"03"
		{
			"var_type"					"FIELD_INTEGER"
			"damage"					"200 300 400 500 575 625 675"
		}
		"04"
		{
			"var_type"					"FIELD_FLOAT"
			"burn_duration"				"5"
		}	
		"05"
		{
			"var_type"					"FIELD_INTEGER"
			"building_damage_pct"		"50"
		}	
		"06"
		{
			"var_type"					"FIELD_FLOAT"
			"activation_delay"			"1.22"
		}
		"07"
		{
			"var_type"					"FIELD_INTEGER"
			"cast_range_scepter_bonus"	"300"
			"RequiresScepter"			"1"
		}
		"08"
		{
			"var_type"					"FIELD_FLOAT"
			"AbilityChargeRestoreTime"	""
			"LinkedSpecialBonus"		"special_bonus_unique_techies_3"
		}
		"09"
		{
			"var_type"					"FIELD_FLOAT"
			"damage_pct"				"5.0"
		}
	}
}

//=================================================================================================================
// Techies: Stasis Trap
//=================================================================================================================
"techies_stasis_trap"
{
	"MaxLevel"						"7"

	// Casting
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCastRange"				"150"
	"AbilityCastPoint"				"0.0"
	
	// Time		
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCooldown"				"20.0 18.0 16.0 14.0 13.0 10.0 8.0"

	// Cost
	//-------------------------------------------------------------------------------------------------------------
	"AbilityManaCost"				"80 110 140 160 180 200 220"

	// Special
	//-------------------------------------------------------------------------------------------------------------
	"AbilitySpecial"
	{		
		"01"
		{
			"var_type"					"FIELD_INTEGER"
			"activation_radius"			"390"
		}
		"02"
		{
			"var_type"					"FIELD_FLOAT"
			"explode_delay"				"0.75"
		}
		"03"
		{
			"var_type"					"FIELD_INTEGER"
			"stun_radius"				"450"
		}
		"04"
		{
			"var_type"					"FIELD_FLOAT"
			"stun_duration"				"2.5 2.7 2.9 3.1 3.3 3.5 3.7"
		}
		"05"
		{
			"var_type"					"FIELD_FLOAT"
			"activation_time"			"0.1"
		}	
		"06"
		{
			"var_type"					"FIELD_FLOAT"
			"fade_time"					"2.0"
		}
		"07"
		{
			"var_type"					"FIELD_FLOAT"
			"duration"					"360.0"
		}
	}
}

//=================================================================================================================
// Techies: Remote Mines
//=================================================================================================================
"techies_remote_mines"
{
	"MaxLevel"						"7"

	// Casting
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCastRange"				"500"
	"AbilityCastPoint"				"0.5"
	
	// Time		
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCooldown"				"6.0"

	// Cost
	//-------------------------------------------------------------------------------------------------------------
	"AbilityManaCost"				"150 175 200 225 250 275 300"

	// Special
	//-------------------------------------------------------------------------------------------------------------
	"AbilitySpecial"
	{
		"01"
		{
			"var_type"					"FIELD_INTEGER"
			"max_mines"					"2400"
		}
		"02"
		{
			"var_type"					"FIELD_INTEGER"
			"damage"					"275 325 450 650 820 925 1000"
		}
		"03"
		{
			"var_type"					"FIELD_INTEGER"
			"radius"					"425"
		}		
		"04"
		{
			"var_type"					"FIELD_FLOAT"
			"duration"					"9999999.0"
		}
		"05"
		{
			"var_type"					"FIELD_FLOAT"
			"activation_time"			"2.0"
		}	
		"06"
		{
			"var_type"					"FIELD_INTEGER"
			"damage_scepter"			"300 375 500 700 850 950 1150"
			"RequiresScepter"			"1"
		}
		"07"
		{
			"var_type"					"FIELD_INTEGER"
			"radius_scepter"			"425"
			"RequiresScepter"			"1"
		}
		"08"
		{
			"var_type"					"FIELD_INTEGER"
			"cast_range_scepter_bonus"	"500"
			"RequiresScepter"			"1"
		}			
		"09"
		{
			"var_type"					"FIELD_INTEGER"
			"vision_radius"				"500"
		}
		"10"
		{
			"var_type"					"FIELD_FLOAT"
			"vision_duration"			"3.0"
		}
		"11"
		{
			"var_type"					"FIELD_INTEGER"
			"model_scale"				"15"     // Percentage over model scale
		}
		"12"
		{
			"var_type"					"FIELD_FLOAT"
			"detonate_delay"			"0.25"
		}
		"13"
		{
			"var_type"					"FIELD_FLOAT"
			"damage_pct"				"15"
			"CalculateSpellDamageTooltip" "0"
		}
	}
}



//=================================================================================================================
// Ability: Minefield Sign
//=================================================================================================================
"techies_minefield_sign"
{
	"MaxLevel"						"1"

	// Time		
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCooldown"				"60.0"
	
	// Cost
	//-------------------------------------------------------------------------------------------------------------
	"AbilityManaCost"				"100"
	
	// Special	
	//-------------------------------------------------------------------------------------------------------------
	"AbilitySpecial"
	{
		"01"
		{
			"var_type"					"FIELD_INTEGER"
			"aura_radius"				"300"
			"RequiresScepter"			"1"
		}
		"02"
		{
			"var_type"					"FIELD_INTEGER"
			"lifetime"					"50"
		}
	}
}

"techies_suicide"
{
	"MaxLevel"						"7"
	
	// Casting
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCastRange"				"1000"
	"AbilityCastPoint"				"1.0"

	// Time		
	//-------------------------------------------------------------------------------------------------------------
	"AbilityCooldown"				"10"

	// Cost
	//-------------------------------------------------------------------------------------------------------------
	"AbilityManaCost"				"100 125 150 175 200 225 250"

	// Special
	//-------------------------------------------------------------------------------------------------------------
	"AbilitySpecial"
	{
		"01"
		{
			"var_type"					"FIELD_INTEGER"
			"radius"					"500"
		}
		"02"
		{
			"var_type"					"FIELD_INTEGER"
			"damage"					"100 150 200 250 300 350 400"
			"LinkedSpecialBonus"		"special_bonus_unique_techies"
		}
		"03"
		{
			"var_type"					"FIELD_FLOAT"
			"silence_duration"			"2.0 2.3 2.7 3.0 3.3 3.7 4.0"
		} 
		"04"
		{
			"var_type"					"FIELD_INTEGER"
			"hp_cost"					"25"
		} 
		"05"
		{
			"var_type"					"FIELD_FLOAT"
			"duration"					"0.75"
		}
		"06"
		{
			"var_type"					"FIELD_FLOAT"
			"damage_pct"				"25"
		}
	}
}

//=================================================================================================================
// Ability: Special Bonus
//=================================================================================================================
"special_bonus_unique_techies_4"
{
	"AbilitySpecial"
	{
		"01"
		{
			"var_type"					"FIELD_INTEGER"
			"value"						"50"
			"ad_linked_ability"			"multi_linked_or_ability"
			"linked_ad_abilities"		"techies_land_mines techies_stasis_trap techies_remote_mines"
		}
	}
}

"special_bonus_unique_techies_5"
{
	// General
	//-------------------------------------------------------------------------------------------------------------
	"ID"					"412"														// unique ID number for this ability.  Do not change this once established or it will invalidate collected stats.
	"AbilityType"					"DOTA_ABILITY_TYPE_ATTRIBUTES"
	"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE"

	// Special
	//-------------------------------------------------------------------------------------------------------------
	"AbilitySpecial"
	{
		"01"
		{
			"var_type"					"FIELD_INTEGER"
			"value"						"8"
			"ad_linked_ability"			"techies_suicide"
		}
	}
}
// Ability: Special Bonus
//=================================================================================================================
"special_bonus_unique_techies_4"
{
	// General
	//-------------------------------------------------------------------------------------------------------------
	"AbilityType"					"DOTA_ABILITY_TYPE_ATTRIBUTES"
	"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE"
	
	// Special
	//-------------------------------------------------------------------------------------------------------------
	"AbilitySpecial"
	{
		"01"
		{
			"var_type"					"FIELD_INTEGER"
			"value"						"60"
			"ad_linked_ability"			"multi_linked_or_ability"				   // multi_linked_or_ability means one of the abilities (not all) listed under linked_ad_abilities needs to be present for the talent to be valid.
			"linked_ad_abilities"		"techies_land_mines techies_stasis_trap techies_remote_mines"
		}
	}
}